[package]
name = "fund"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html


[dependencies]
starknet = "2.11.2"

[dev-dependencies]
cairo_test = "2.11.2"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.40.0" }

[[target.starknet-contract]]
name = "beneficiary"
sierra = true
sierra-text = true


[[target.starknet-contract]]
name = "fund"
sierra = true
sierra-text = true

[[target.starknet-contract]]
name = "investment"
sierra = true
sierra-text = true

[[target.starknet-contract]]
name = "payout"
sierra = true
sierra-text = true
